{{- $values := .Values }}

{{- range $index, $middlewareData := .Values.middlewares.addPrefix }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if .Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ $middlewareData.name }}
  namespace: tc-system
spec:
  addPrefix:
    prefix: {{ $middlewareData.prefix }}
{{- end }}
