{{- $values := .Values }}

{{- range $index, $middlewareData := .Values.middlewares.realIP }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if .Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ $middlewareData.name }}
  namespace: tc-system
spec:
  plugin:
    traefik-real-ip:
      excludednets:
        {{- range $middlewareData.excludedNetworks }}
        - {{ . | quote }}
        {{- end }}
{{- end }}
