{{- $values := .Values }}

{{ range $index, $middlewareData := .Values.middlewares.redirectScheme }}

---
# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if .Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ $middlewareData.name }}
  namespace: tc-system
spec:
  redirectScheme:
    scheme: {{ $middlewareData.scheme }}
    permanent: {{ $middlewareData.permanent }}
{{ end }}
