{{- $values := .Values }}

{{- range $index, $middlewareData := .Values.middlewares.themePark }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if .Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ $middlewareData.name }}
  namespace: tc-system
spec:
  plugin:
    traefik-themepark:
      app: {{ $middlewareData.appName }}
      theme: {{ $middlewareData.themeName }}
      baseUrl: {{ $middlewareData.baseUrl }}
      {{- if $middlewareData.addons }}
      addons:
        {{- range $middlewareData.addons }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
{{- end }}
