image:
  repository: tccr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: v1.6.21@sha256:48fe4a716d199b3979ae201b982f849395b6785aa634916bb8576f657f0a5ddf

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
