image:
  repository: tccr.io/truecharts/radarr
  pullPolicy: IfNotPresent
  tag: 4.3.2.6857@sha256:b51ca8472ed45f8979ef4bf86608449d620a7b698c718bbfc57dfbe20af8033a
service:
  main:
    ports:
      main:
        port: 7878
persistence:
  config:
    enabled: true
    mountPath: /config
cnpg:
  main:
    enabled: true

    database: radarr
    user: radarr
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              ## Set this to true if you wish to specify your own livenessProbe
              custom: true
              ## The spec field contains the values for the default livenessProbe.
              ## If you selected custom: true, this field holds the definition of the livenessProbe.
              spec:
                exec:
                  command:
                    - /usr/bin/env
                    - bash
                    - -c
                    - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
                failureThreshold: 5
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
          env:
            RADARR__PORT: "{{ .Values.service.main.ports.main.port }}"
            RADARR__AUTHENTICATION_METHOD: ""
            RADARR__POSTGRES_PORT: 5432
            RADARR__POSTGRES_USER: "{{ .Values.cnpg.main.user }}"
            RADARR__POSTGRES_MAIN_DB: "{{ .Values.cnpg.main.database }}"
            RADARR__POSTGRES_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            RADARR__POSTGRES_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
