image:
  repository: tccr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: v1.6.21@sha256:5d25d26461767404bc05e6c6a0fc880399bd22f4b9f2365984b72c3098a9facf

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
