{{- $values := .Values }}

{{ range $index, $middlewareData := .Values.middlewares.rateLimit }}

---
# Declaring the user list
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if $.Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ if $.Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ $middlewareData.name }}
  namespace: tc-system
spec:
  rateLimit:
    average: {{ $middlewareData.average }}
    burst: {{ $middlewareData.burst }}
{{ end }}
