{{- $values := .Values }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if $.Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ if $.Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}tc-opencors-headers
  namespace: tc-system
spec:
  headers:
    accessControlAllowHeaders:
    - '*'
    accessControlAllowMethods:
    - GET
    - OPTIONS
    - HEAD
    - PUT
    - POST
    accessControlAllowOriginList:
    - '*'
    accessControlMaxAge: 100
    browserXssFilter: true
    contentTypeNosniff: true
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      server: ""
    forceSTSHeader: true
    referrerPolicy: same-origin
    sslForceHost: true
    sslRedirect: true
    stsSeconds: 63072000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ if $.Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}{{ if $.Values.ingressClass.enabled }}{{ .Release.Name }}-{{ end }}tc-closedcors-headers
  namespace: tc-system
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - HEAD
      - PUT
    accessControlMaxAge: 100
    sslRedirect: true
    stsSeconds: 63072000
    # stsIncludeSubdomains: false
    # stsPreload: false
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
    sslForceHost: true
    referrerPolicy: same-origin
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      server: ''
